appName: cartservice

appImage: gcr.io/google-samples/microservices-demo/cartservice

containerPort: 7070

containerEnvVars:
  - name: PORT
    value: "7070"
  - name: REDIS_ADDR
    value: "redis-cart:6379"
  - name: DISABLE_PROFILER
    value: "1"

servicePort: 7070