appName: currencyservice

appImage: gcr.io/google-samples/microservices-demo/currencyservice

containerPort: 7000

containerEnvVars:
  - name: PORT
    value: "7000"
  - name: DISABLE_PROFILER
    value: "1"

servicePort: 7000