appName: emailservice

appImage: gcr.io/google-samples/microservices-demo/emailservice


containerPort: 8080

containerEnvVars:
  - name: PORT
    value: "8080"
  - name: DISABLE_PROFILER
    value: "1"


servicePort: 8080


  

