appName: paymentservice

appImage: gcr.io/google-samples/microservices-demo/paymentservice

containerPort: 50051

containerEnvVars:
  - name: PORT
    value: "50051"
  - name: DISABLE_PROFILER
    value: "1"

servicePort: 50051