appName: recommendationservice

appImage: gcr.io/google-samples/microservices-demo/recommendationservice

containerPort: 8080

containerEnvVars:
  - name: PORT
    value: "8080"
  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
  - name: DISABLE_PROFILER
    value: "1"

servicePort: 8080